### ISSUE TITLE
Lady Monita features to port

### ISSUE THREAD

**Issue by sirDonovan** [sirDonovan/Lanette#3]
**Client**
- [x] Support chat moderation
- [x] Room modchat tracking
- [x] Ignore PMs from locked and namelocked users

**Games**
- [x] Scripted games
- [x] User-hosted games
- - [x] basic implementation
- - [x] host commands
- - [x] different signups HTML
- [x] Templates
- [x] Variants
- [x] Modes
- [x] Achievements
- [x] 1v1 challenges
- [x] Parameter finder
- [x] Portmanteau finder
- [x] Chill time
- [x] .vote
- [x] Format cooldowns
- [x] Format description commands
- [x] Minigames

**Storage**
- [x] Databases
- - [x] basic implementation
- - [x] transferData()
- [x] Leaderboards
- - [x] basic implementation
- - [x] clearLeaderboard()
- - [x] .rank
- [x] Chat logging
- [x] Mail
- [x] .seen

**Tools**
- [x] Format info display

**Tournaments**
- [x] Official tournaments
- [x] .tour
- [x] .nexttour
- [x] Custom rules
- [x] Announcements in other rooms
- [x] Auto-setting cap
- [x] Challonge approval process

**Comment by DeanRyder** [comment]
Mr. Donovan, I would like you to know that I love your bot and was using it on Pokémon Showdown but when I mailed an already offline user it said that the user needs to be offline to send her a mail however the error didn't show up when i mailed someone else. Any Suggestions as to why it occurred?

**Comment by sirDonovan** [comment]
@DeanRyder thanks! The user you tried to send the message to may have been online in a room that you weren't in. If it happens again, you can do <code>/user [name]</code> to verify that they are offline.

**Comment by DeanRyder** [comment]
Thank you very much, sir. Sorry to have taken your time and enjoy the rest
of your day.

**Comment by sirDonovan** [comment]
With https://github.com/sirDonovan/Lanette/pull/12 this is now complete!
